version: "3"
services:
  bot:
    image: "golang:1.16.7-alpine3.14"
    environment:
      BROKER_HOST: "broker"
      BROKER_PORT: "1883"
      BROKER_TOPIC: $BROKER_TOPIC
      DISCORD_BOT_ID: $DISCORD_BOT_ID
      DISCORD_TRIGGER_EMOJI: $DISCORD_TRIGGER_EMOJI
    volumes:
      - "./bot:/workspace"
    working_dir: "/workspace"
    command: >
      sh -c '
      go build -o /usr/local/bin/bot &&
      /usr/local/bin/bot'
    depends_on:
      - "broker"
  broker:
    image: "eclipse-mosquitto:2.0.11"
    volumes:
      - "./broker/config:/mosquitto/config"
      - "./broker/data:/mosquitto/data"
      - "./broker/log:/mosquitto/log"
    ports:
      - "1883:1883"
    expose:
      - "1883"
    user: "1000:1000"
